# add here runtime options, one per line
-Dprism.lcdtext=false
-Dorg.pdfsam.default.checkforupdate=false
-Dorg.pdfsam.default.donate.notification=false
-Dorg.pdfsam.default.locale=cs
-Dorg.pdfsam.default.checkfornews=false
-Dorg.pdfsam.default.play.sounds=false
-Dorg.pdfsam.default.fetch.premium.modules=false
